name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to read the repository contents
      pages: write # Required to deploy to GitHub Pages
      id-token: write # Required for authentication with GitHub Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Docusaurus site
        run: pnpm run build

      # Must run in the same job, otherwise previous output won't be kept
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build" # Default output directory for Docusaurus build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
